### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hshindo** [chakki-works/chaFiC#1]
The following files are missing.

* [https://s3-ap-northeast-1.amazonaws.com/chakki.esg.financial.jp/dataset/release/chakki_esg_financial_extracted_2018.zip]()
* [https://s3-ap-northeast-1.amazonaws.com/chakki.esg.financial.jp/dataset/release/chakki_esg_financial_extracted_2018.zip]()

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. I fixed the access control of the file.
